### ISSUE TITLE
what's the meaning of 80pct, 90pct & rate

### ISSUE THREAD

**Issue by FrancisJen** [cgoldberg/multi-mechanize#51]
I see 80pct and rate in the performance testing report, but there is no any introduction in doc, Could you please help to clarify?

1.what 's the basis of 80pct, the transaction number or the max response time?
2.what is the meaning of rate?

**Comment by sixiong** [comment]
I think it means top 80% less than ‘x'

**Comment by cgoldberg** [comment]
1. 80pct means 80th percentile.
2. rate is transactions per second.
