### ISSUE TITLE
can not find test script: v_user.py

### ISSUE THREAD

**Issue by vieyahn** [cgoldberg/multi-mechanize#52]
multimech-newproject my_project
multimech-run my_project
i don't change everything, ( v_user.py  config.cfg ) but also meet this problem.

ERROR: can not find test script: v_user.py.  aborting user group: user_group-1
ERROR: can not find test script: v_user.py.  aborting user group: user_group-1
ERROR: can not find test script: v_user.py.  aborting user group: user_group-1

**Comment by vieyahn** [comment]
my system is  win7 64bit.
my python version is 2.7

**Comment by vieyahn** [comment]
my system is  win7 64bit.
my python version is 2.7

**Comment by jiftle** [comment]
me too.
my system is win7-x64
my python version is 2.7.

from china.

**Comment by cgoldberg** [comment]
I am no longer supporting this project.
